version: '3.9'
services:
  mongodb:
    image: mongo:5.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: spring-test # Nome do banco de dados
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/spring-test
    depends_on:
      - mongodb
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
